const GOVERNORATES=["Ariana","Béja","Ben Arous","Bizerte","Gabès","Gafsa","Jendouba","Kairouan","Kasserine","Kébili","Le Kef","Mahdia","La Manouba","Médenine","Monastir","Nabeul","Sfax","Sidi Bouzid","Siliana","Sousse","Tataouine","Tozeur","Tunis","Zaghouan"];
const COLORS={official:'#7a4fd1',confirmed:'#e23b4c',probable:'#ef9b21',restored:'#1b9b64'};
const LABELS={official:'Annonce officielle',confirmed:'Coupure confirmée',probable:'Coupure probable',restored:'Courant rétabli'};
const seed=[
{id:'sfax-1',zone:'Sakiet Ezzit',governorate:'Sfax',lat:34.80,lng:10.77,status:'confirmed',confidence:91,reports:18,sensors:3,official:false,started:'2026-07-23T09:12:00',duration:'48 min'},
{id:'tunis-1',zone:'El Menzah 6',governorate:'Tunis',lat:36.84,lng:10.17,status:'probable',confidence:63,reports:7,sensors:1,official:false,started:'2026-07-23T09:47:00',duration:'21 min'},
{id:'nabeul-1',zone:'Hammamet Nord',governorate:'Nabeul',lat:36.41,lng:10.61,status:'official',confidence:100,reports:11,sensors:2,official:true,started:'2026-07-23T08:30:00',duration:'Maintenance 2 h'},
{id:'sousse-1',zone:'Sahloul',governorate:'Sousse',lat:35.83,lng:10.59,status:'restored',confidence:88,reports:14,sensors:2,official:false,started:'2026-07-23T07:05:00',duration:'37 min'},
{id:'bizerte-1',zone:'Menzel Bourguiba',governorate:'Bizerte',lat:37.15,lng:9.79,status:'confirmed',confidence:84,reports:12,sensors:2,official:false,started:'2026-07-23T09:34:00',duration:'29 min'},
{id:'gabes-1',zone:'Gabès Sud',governorate:'Gabès',lat:33.85,lng:10.10,status:'probable',confidence:57,reports:5,sensors:0,official:false,started:'2026-07-23T10:02:00',duration:'15 min'}];
let incidents=JSON.parse(localStorage.getItem('dhawna-incidents')||'null')||seed;
let map,markers=new Map();
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
function fmtDate(v){return new Intl.DateTimeFormat('fr-TN',{hour:'2-digit',minute:'2-digit'}).format(new Date(v))}
function save(){localStorage.setItem('dhawna-incidents',JSON.stringify(incidents))}
function fillSelects(){const gov=$('#governorate-filter'),report=$('#report-governorate');GOVERNORATES.forEach(g=>{gov.insertAdjacentHTML('beforeend',`<option>${g}</option>`);report.insertAdjacentHTML('beforeend',`<option>${g}</option>`)})}
function filtered(){const g=$('#governorate-filter').value,s=$('#status-filter').value;return incidents.filter(i=>(g==='all'||i.governorate===g)&&(s==='all'||i.status===s))}
function renderStats(){const active=incidents.filter(i=>i.status!=='restored');$('#active-incidents').textContent=active.length;$('#watched-zones').textContent=new Set(incidents.map(i=>i.zone)).size;$('#powered-zones').textContent=incidents.filter(i=>i.status==='restored').length;$('#reports-today').textContent=incidents.reduce((a,i)=>a+i.reports,0);$('#last-update').textContent=new Intl.DateTimeFormat('fr-TN',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date());$('#citizen-source-count').textContent=incidents.reduce((a,i)=>a+i.reports,0);$('#sensor-source-count').textContent=incidents.reduce((a,i)=>a+i.sensors,0);$('#official-source-count').textContent=incidents.filter(i=>i.official).length}
function renderList(){const data=filtered(),box=$('#incident-list');box.innerHTML=data.length?'':'<p class="muted">Aucun incident pour ces filtres.</p>';data.forEach(i=>box.insertAdjacentHTML('beforeend',`<article class="incident-item" data-id="${i.id}"><div class="incident-top"><div><h3>${i.zone}</h3><p>${i.governorate} · depuis ${fmtDate(i.started)}</p></div><span class="status-badge ${i.status}">${LABELS[i.status]}</span></div><div class="incident-meta"><span>${i.reports} citoyens · ${i.sensors} capteur(s)</span><span class="confidence">${i.confidence}% confiance</span></div></article>`));$$('.incident-item').forEach(el=>el.onclick=()=>focusIncident(el.dataset.id));renderMarkers(data)}
function initMap(){try{if(!window.L)throw Error('Leaflet absent');map=L.map('map',{zoomControl:false}).setView([34.4,9.4],6);L.control.zoom({position:'topright'}).addTo(map);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; OpenStreetMap'}).addTo(map);renderMarkers(filtered())}catch(e){$('#map').hidden=true;$('#map-fallback').hidden=false}}
function renderMarkers(data){if(!map)return;markers.forEach(m=>m.remove());markers.clear();data.forEach(i=>{const icon=L.divIcon({className:'',html:`<div style="width:22px;height:22px;border:4px solid white;border-radius:50%;background:${COLORS[i.status]};box-shadow:0 3px 15px rgba(0,0,0,.35)"></div>`,iconSize:[22,22],iconAnchor:[11,11]});const m=L.marker([i.lat,i.lng],{icon}).addTo(map).bindPopup(`<strong>${i.zone}</strong><br>${LABELS[i.status]}<br><b>${i.confidence}%</b> de confiance<br>${i.reports} signalements`);markers.set(i.id,m)})}
function focusIncident(id){const i=incidents.find(x=>x.id===id);$$('.incident-item').forEach(e=>e.classList.toggle('selected',e.dataset.id===id));if(map&&i){map.flyTo([i.lat,i.lng],11,{duration:.8});markers.get(id)?.openPopup()}}
function renderHistory(){const body=$('#history-table');body.innerHTML='';[...incidents].sort((a,b)=>new Date(b.started)-new Date(a.started)).forEach(i=>body.insertAdjacentHTML('beforeend',`<tr><td><strong>${i.zone}</strong><br><small>${i.governorate}</small></td><td><span class="status-badge ${i.status}">${LABELS[i.status]}</span></td><td>${fmtDate(i.started)}</td><td>${i.duration}</td><td>${i.confidence}%</td><td>${i.reports} citoyens · ${i.sensors} capteurs</td></tr>`))}
function renderReliability(){const vals={Sfax:72,Tunis:84,Nabeul:79,Sousse:88,Bizerte:76,Gabès:81};$('#reliability-bars').innerHTML=Object.entries(vals).map(([g,v])=>`<div class="bar-row"><strong>${g}</strong><div class="bar-track"><div class="bar-fill" style="width:${v}%"></div></div><span>${v}/100</span></div>`).join('')}
function switchView(id){$$('.app-view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='history-view')renderHistory();if(id==='dashboard-view')renderReliability();if(id==='map-view')setTimeout(()=>map?.invalidateSize(),50)}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
function openReport(){if(typeof $('#report-dialog').showModal==='function')$('#report-dialog').showModal()}
function submitReport(e){e.preventDefault();const status=document.querySelector('[name="report-status"]:checked')?.value;if(!status)return;const gov=$('#report-governorate').value,zone=$('#report-zone').value.trim();const coords={Sfax:[34.74,10.76],Tunis:[36.81,10.18],Sousse:[35.83,10.64],Nabeul:[36.45,10.74],Bizerte:[37.27,9.87],Gabès:[33.88,10.10]}[gov]||[34.2+Math.random()*2,9+Math.random()*2];const mapped=status==='powered'||status==='restored'?'restored':'probable';const found=incidents.find(i=>i.governorate===gov&&i.zone.toLowerCase()===zone.toLowerCase());if(found){found.reports++;found.confidence=Math.min(99,found.confidence+5);found.status=mapped}else incidents.unshift({id:crypto.randomUUID(),zone,governorate:gov,lat:coords[0],lng:coords[1],status:mapped,confidence:mapped==='restored'?72:42,reports:1,sensors:0,official:false,started:new Date().toISOString(),duration:'À confirmer'});save();renderAll();$('#report-dialog').close();e.target.reset();toast('Merci — votre signalement a été pris en compte.')}
function exportCSV(){const rows=[['Zone','Gouvernorat','Statut','Confiance','Signalements','Capteurs','Début'],...incidents.map(i=>[i.zone,i.governorate,LABELS[i.status],i.confidence,i.reports,i.sensors,i.started])];const csv=rows.map(r=>r.map(x=>`"${String(x).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='dhawna-incidents.csv';a.click();URL.revokeObjectURL(a.href)}
function locate(){if(!navigator.geolocation)return toast('Géolocalisation non disponible.');navigator.geolocation.getCurrentPosition(p=>{map?.flyTo([p.coords.latitude,p.coords.longitude],12);L.circleMarker([p.coords.latitude,p.coords.longitude],{radius:8}).addTo(map).bindPopup('Votre position approximative').openPopup()},()=>toast('Impossible d’accéder à votre position.'))}
function renderAll(){renderStats();renderList();renderHistory();renderReliability()}
fillSelects();renderAll();initMap();$$('.nav-link').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-open-report]').forEach(b=>b.onclick=openReport);$$('[data-close-report]').forEach(b=>b.onclick=()=>$('#report-dialog').close());$('#report-form').addEventListener('submit',submitReport);$('#governorate-filter').onchange=renderList;$('#status-filter').onchange=renderList;$('#export-button').onclick=exportCSV;$('#locate-button').onclick=locate;$('#theme-toggle').onclick=()=>{const dark=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=dark?'light':'dark';localStorage.setItem('dhawna-theme',dark?'light':'dark')};document.documentElement.dataset.theme=localStorage.getItem('dhawna-theme')||'light';if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));